### ISSUE TITLE
Parsing net/tcp

### ISSUE THREAD

**Issue by maartenJacobs** [erikd/system-linux-proc#1]
I'm interested in extracting ports of a process from `/proc/<pid>/net/tcp`. Any thoughts on adding a module for net/tcp? I'm happy to contribute as this library seems laid out nicely.

**Comment by erikd** [comment]
Sure. If its in the Linux `/proc/` filesystem I am happy to have this library support it.

**Comment by maartenJacobs** [comment]
Closing this as it's now part of 0.1.1.0. Thanks @erikd :tada:
