### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thomasjm** [erikd/system-linux-proc#10]
It would be nice to have a new release compatible with recent libraries such as `text-2.x`, `bytestring-0.11.x`, etc.

AFAIK the only thing that needs to be done is relax some bounds.

**Comment by erikd** [comment]
I updated all dependencies to the latest versions on Hackage (tested them locally first). 

Thanks!

**Comment by thomasjm** [comment]
Hi @erikd, I just tried to use this and ran into a problem --

It looks like the latest version on Hackage ([0.1.1.1](https://hackage.haskell.org/package/system-linux-proc-0.1.1.1)) doesn't support `text-2.x`?

FWIW I've been running a fork that drops the `text` bound and it seems to work fine. Any chance you could do a revision for this as well?

**Comment by erikd** [comment]
Sorry, I must have messed up. Should be fixed now.

**Comment by thomasjm** [comment]
Thanks! I'll check in a few hours since it seems to take a while for the revision to percolate through Hackage's servers...

Incidentally, would you object to trying to get this package onto Stackage? I'd be happy to be responsible for it.

**Comment by erikd** [comment]
I have no issue with it being in Stackage as long as I don't have be responsible for it. It you want to be responsible, go for it.
