### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by Artturin** [erikd/system-linux-proc#9]
so that 857377ec65d8ea354dfc093f7cdfe6fc74e0af40 is in a release
currently this library is marked as broken in nixpkgs since the containers version in nixpkgs is 0.6.5.1 and the build of this fails with
```
system-linux-proc> Setup: Encountered missing or private dependencies:
system-linux-proc> containers ==0.5.*
```

**Comment by erikd** [comment]
Should be on Hackage now.

**Comment by Artturin** [comment]
Thanks
